# Generated by Django 4.1.2 on 2022-11-05 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='segment',
            field=models.CharField(max_length=1000),
        ),
    ]
